---
# Adapted from playbook found here and clang docs: https://github.com/loderunner/ansible-clang
# Clang apt install info here: https://apt.llvm.org/
- name: Install Clang LLVM compiler
  connection: ssh
  gather_facts: false
  hosts: all
  vars:
    - present_state: "present"
  tasks:
    - name: Add LLVM APT key
      become: "yes"
      apt_key:
        url: https://apt.llvm.org/llvm-snapshot.gpg.key
    - name: Add LLVM APT repository
      become: "yes"
      apt_repository:
        repo: deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic main
        update_cache: yes
    - name: Install a Clang 7
      become: "yes"
      apt:
        name: "{{ packages }}"
        update_cache: "yes"
        state: "{{ present_state }}"
      vars:
        packages:
        - clang-7
        - lldb-7
        - lld-7
    - name: Install a Clang 7 Key Packages LLVM
      become: "yes"
      apt:
        name: "{{ packages }}"
        update_cache: "yes"
        state: "{{ present_state }}"
      vars:
        packages:
        - libllvm-7-ocaml-dev
        - libllvm7
        - llvm-7
        - llvm-7-dev
        - llvm-7-doc
        - llvm-7-examples
        - llvm-7-runtime
    - name: Install a Clang 7 Key Packages Clang and co
      become: "yes"
      apt:
        name: "{{ packages }}"
        update_cache: "yes"
        state: "{{ present_state }}"
      vars:
        packages:
        - clang-7
        - clang-tools-7
        - clang-7-doc
        - libclang-common-7-dev
        - libclang-7-dev
        - libclang1-7
        - clang-format-7
        - python-clang-7
    - name: Install a Clang 7 Key Packages libfuzzer
      become: "yes"
      apt:
        name: "{{ packages }}"
        update_cache: "yes"
        state: "{{ present_state }}"
      vars:
        packages:
        - libfuzzer-7-dev
    - name: Install a Clang 7 Key Packages libfuzzer
      become: "yes"
      apt:
        name: "{{ packages }}"
        update_cache: "yes"
        state: "{{ present_state }}"
      vars:
        packages:
        - lldb-7
    - name: Install a Clang 7 Key Packages lld (linker)
      become: "yes"
      apt:
        name: "{{ packages }}"
        update_cache: "yes"
        state: "{{ present_state }}"
      vars:
        packages:
        - lld-7
    - name: Install a Clang 7 Key Packages libc++
      become: "yes"
      apt:
        name: "{{ packages }}"
        update_cache: "yes"
        state: "{{ present_state }}"
      vars:
        packages:
        - libc++-7-dev
        - libc++abi-7-dev
    - name: Install a Clang 7 Key Packages OpenMP
      become: "yes"
      apt:
        name: "{{ packages }}"
        update_cache: "yes"
        state: "{{ present_state }}"
      vars:
        packages:
        - libomp-7-dev

- name: Export LLVM_CONFIG on Primary Node's bashrc for ansible_ssh_user
  connection: ssh
  gather_facts: "no"
  hosts: jetson_nano_primary
  tasks:
    - name: Ensure export of llvm-config PATH
      # become: "yes"
      lineinfile:
        dest: "/home/{{ ansible_ssh_user }}/.bashrc"
        # regexp="^export PATH=$PATH:$SPARK_HOME\s"
        line: 'export LLVM_CONFIG=/usr/bin/llvm-config-7'
