---
## Adapted from example here: https://gist.github.com/glennswest/6e43aa88f3de0a0cf4ecf00749a91fa1
- name: Configure Inventory Names as Hostnames in /etc/hosts
  hosts: all
  connection: ssh
  gather_facts: True
  tasks:
  - name: check connection
    ping:
  - name: setup
    setup:
  - name: "Build hosts file"
    become: "yes"
    lineinfile: dest=/etc/hosts
                state=present
                dest=/etc/hosts
                regexp='.*{{ item }}$' line="{{ hostvars[item].ansible_default_ipv4.address }} {{item}}"
    when: hostvars[item].ansible_default_ipv4.address is defined
    with_items: "{{ groups['all'] }}"
