---
- name: Install Linpack Prerequisites
  connection: ssh
  gather_facts: false
  hosts: all
  tasks:
    - name: Install prerequisites for Linpack Benchmark
      become: "yes"
      apt:
        name: "{{ packages }}"
        update_cache: "yes"
      vars:
        packages:
        - libblas-dev
        - gfortran
