---
- name: Install configure unified NFS Home mount and SSH keys between nodes
  connection: ssh
  gather_facts: "yes"
  hosts: jetson_nano_primary
  vars:
    ip_address: "{{ ansible_default_ipv4.address }}/{{ ansible_default_ipv4.netmask }}"
    subnet: "{{ ip_address | ipaddr('network/prefix') }}"
  tasks:
    - name: Install NFS server package
      become: "yes"
      apt:
        name: "{{ packages }}"
        update_cache: "yes"
      vars:
        packages:
        - nfs-kernel-server
    - name: Ensure exported directory /home is in /etc/exports
      become: "yes"
      lineinfile: dest=/etc/exports
                  regexp="^/home\s"
                  line='/home      {{subnet}}(rw,sync,no_root_squash,no_subtree_check)'
      # notify: refresh exports
    - name: Restart service nfs
      become: "yes"
      service:
        name: nfs-kernel-server
        state: restarted
    - name: Create a 4096-bit SSH key for user '{{ansible_ssh_user}}' in ~'{{ansible_ssh_user}}'/.ssh/id_rsa
      user:
        name: '{{ansible_ssh_user}}'
        generate_ssh_key: yes
        ssh_key_bits: 4096
        ssh_key_file: .ssh/id_rsa
    - name: export public ssh key
      shell: cat ~/.ssh/id_rsa.pub
      register: ssh_keys
      tags:
        - ssh
    - name: add ssh keys to authorized keys
      authorized_key:
        user: '{{ansible_ssh_user}}'
        key: "{{ ssh_keys.stdout }}"
        state: present
      tags:
        - ssh

    - debug: var="{{ subnet }}"

- name: Install configure unified NFS Home mount
  connection: ssh
  gather_facts: "yes"
  hosts: jetson_nano_worker
  vars:
    primary_ip: "{{ hostvars['jn1']['ansible_default_ipv4']['address'] }}"
  tasks:
    - name: Install NFS client package
      become: "yes"
      apt:
        name: "{{ packages }}"
        update_cache: "yes"
      vars:
        packages:
        - nfs-common
    - name: Mount NFS home directory
      become: "yes"
      mount:
        path: /home
        src: '{{ primary_ip }}:/home'
        fstype: nfs
        opts: defaults
        state: mounted
